daemon:
  build: .
  environment:
    - HOSTS=server

  links:
    - server

server:
  build: .
  dockerfile: Dockerfile.server 
  ports:
    - "2222:22"
  volumes:
    - "./docker/id_rsa.pub:/root/.ssh/authorized_keys"
